### ISSUE TITLE
Implement `has` on `StoreGetXXX`

### ISSUE THREAD

**Issue by maoueh** [streamingfast/substreams-rs#13]
Today we have `StoreGet` with the following definition:

```
pub trait StoreGet<T> {
    fn new(idx: u32) -> Self;
    fn get_at<K: AsRef<str>>(&self, ord: u64, key: K) -> Option<T>;
    fn get_last<K: AsRef<str>>(&self, key: K) -> Option<T>;
    fn get_first<K: AsRef<str>>(&self, key: K) -> Option<T>;
}
```

And then some specialized implementation of this trait like `StoreGetProto` that will automatically process the output and decode it to the specified proto message.

However, in some cases, we only care if a specific key is present like when implementing "dynamic data source" pattern on Ethereum. In those cases, we often don't need the actual data and we only want to determine if we should process the output of not.

This task is about adding `fn has<K: AsRef<str>>(&self, ord: u64, key: K) -> bool` support in `StoreGet` and for all concrete implementations. The method should only check if the key exists and avoid all decoding related to it.

- [x] Add support for `has` method on `StoreGet` (Add proper Rust documentation on the method `has` on the trait!).
- [x] Update the CHANGELOG.
- [x] Update `substreams-uniswap-v3` to make use of this where it make sense.
- [ ] Maybe we should add a note on `substreams` CHANGELOG so this change is more discoverable

**Comment by colindickson** [comment]
@maoueh i propose to change the method name to `has_at` since it has essentially the same signature as `get_at`

**Comment by colindickson** [comment]
will be implementing `has_at`, `has_first` and `has_last` to mirror the `get_` methods

**Comment by colindickson** [comment]
done on `unstable`
